# Generated by Django 3.2.19 on 2023-07-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='restaurant_name',
            new_name='name',
        ),
    ]
